{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
  ports:
    - name: redis
      protocol: TCP
      port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
{{- end }}
